apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cronjobs
  namespace: bstage
  description: Bstage cronjobs
  tags:
    - java
  links:
    - url: https://flog.booking.com/?persona=b-bstage-cronjobs
      title: fl
      icon: group
    - url: https://kuhub.prod.booking.com/#/projects/bstage/services/cronjobs
      title: Kuhub
      icon: group
  annotations:
    booking.com/project: bstage
    booking.com/component: cronjobs
    backstage.io/kubernetes-label-selector: service-directory.project=bstage,service-directory.service=cronjobs
    backstage.io/managed-by-location: url:https://services.booking.com/project/bstage/component/cronjobs
    backstage.io/kubernetes-namespace: bstage
    gitlab.com/project-id: '45704676' #1234. This must be in quotes and can be found under Settings --> General
    sonarqube.org/project-key: bookingcomflights-app
    github.com/project-slug: gksinghjsr/bstage_configs
    dynatrace.com/dynatrace-entity-id: fd5fb239-284e-4eb0-8a1b-ea1739ed2639
    jira/project-key: SERDIR
    jira/token-type: Bearer
    grafana/dashboard-selector: 1amfEPjVz
    grafana/tag-selector: "tags @> 'bstage'"
        # or
#     gitlab.com/project-slug: 'gysingh/opa' # group_name/project_name
    # backstage.io/linguist: 'https://github.com/backstage/backstage/tree/master/plugins/playlist'
spec:
  type: service
  lifecycle: production
  owner: team:60003948
  system: bstage-cronjobs
  dependsOn: ['resource:artists-db']
  apiConsumedBy: ['component:www-artist']
