apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: api
  description: Bstage api
  tags:
    - java
  links:
    - url: https://f.b.com/?persona=b-bstage-api
      title: fl
      icon: group
    - url: https://kuhub.prod.booking.com/#/projects/bstage/services/api
      title: Kuhub
      icon: group
  annotations:
    booking.com/project: bstage
    booking.com/component: api
    backstage.io/kubernetes-label-selector: service-directory.project=bstage,service-directory.service=api
    backstage.io/managed-by-location: url:https://services.booking.com/project/bstage/component/api
    backstage.io/kubernetes-namespace: bstage
    # backstage.io/linguist: 'https://github.com/backstage/backstage/tree/master/plugins/playlist'
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: bstage-api
  dependsOn: ['resource:artists-db']
  apiConsumedBy: ['component:www-artist']
